### ISSUE TITLE
Can I use this tool to merge two openapi specs?

### ISSUE THREAD

**Issue by lezhnev74** [javanile/yamlinc#12]
Hi!
Let's say that two people develop two independent API documents (each has standard openapi schema: `openapi`, `info`, `paths`). Does this tool merge these two files into a single openapi spec?

**Comment by francescobianco** [comment]
Hi! 

Yes, you can do it.
A possible approach is: create a file with include list

```yaml
## marge-all-this-files.yml
$include: api-spec-from-jhon.yml
$include: api-spec-from-mark.yml
$include: api-spec-from-erik.yml
```
now run yamlinc

```
$ yamlinc marge-all-this-files.yml
```
