### ISSUE TITLE
yamlinc changes example dates when merging

### ISSUE THREAD

**Issue by StephenNay** [javanile/yamlinc#24]
Here's a piece of a request definition in one of my source files:

```
      - name: date
        description: The date
        in: path
        required: true
        schema:
          type: string
          format: date
        example: 2019-12-25
```

And here's the same section after merging with yamlinc:

```
        - name: date
          description: The date
          in: path
          required: true
          schema:
            type: string
            format: date
          example: '2019-12-25T00:00:00.000Z'
```

Note how the example date in the last line has been changed from just the date to a full date and time format, which is not what I want in this case. Is there a way to prevent this from happening?
