### ISSUE TITLE
excessive quoting

### ISSUE THREAD

**Issue by jason-henriksen** [javanile/yamlinc#28]
input yaml:
```
  OrdersCancel:
    Type: AWS::Serverless::Function

```
output yaml:
```
OrdersCancel:
  Type: **'**AWS::Serverless::Function**'**

```

Because of this I get the following error message when trying to use the cloudformation yaml:
`Error: Template does not have any APIs connected to Lambda functions`

Additionally:
input yaml:
```
Globals:
  Api:
    # Allows an application running locally on port 8080 to call this API
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

```

output yaml:
```
Globals:
  Api:
    Cors:
      AllowMethods: '''*'''
      AllowHeaders: '''*'''
      AllowOrigin: '''*'''

```

Why are my double quotes being randomly turned into single quotes?
